
<div class="heading-contact">
   <h3>Contact Us</h3>
   <p> <a href="home.php">Home</a> / Contact </p>
</div>

<section class="contact">

   <h1 class="title">Get In Touch</h1>

   <form action="" method="POST">
      <input type="text" name="name" class="box" required placeholder="Enter Your Name">
      <input type="email" name="email" class="box" required placeholder="Enter Your Email">
      <input type="number" name="number" min="0" class="box" required placeholder="Enter Your Number">
      <textarea name="msg" class="box" required placeholder="Enter Your Message" cols="30" rows="10"></textarea>
      <input type="submit" value="send message" class="btn" name="send">
   </form>

</section>

<?php include 'footer.phtml'; ?>

<script src="js/script.js"></script>

</body>
</html>