<section class="home-category">

   <h1 class="title">shop by category</h1>

   <div class="box-container">

      <div class="box">
         <img src="images/watch-2.webp" alt="">
         <h3>Fashion Item</h3>
         <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem, quaerat.</p>
         <a href="category.php?category=fashion-item" class="btn">FASHION ITEM</a>
      </div>

      <div class="box">
         <img src="images/cloth-2.jpg" alt="">
         <h3>Clothes</h3>
         <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem, quaerat.</p>
         <a href="category.php?category=clothes" class="btn">CLOTHES</a>
      </div>

      <div class="box">
         <img src="images/cloth-3.jpg" alt="">
         <h3>Shoes</h3>
         <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem, quaerat.</p>
         <a href="category.php?category=shoes" class="btn">SHOES</a>
      </div>

      <div class="box">
         <img src="images/cloth-4.jpg" alt="">
         <h3>Electronics</h3>
         <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem, quaerat.</p>
         <a href="category.php?category=electronics" class="btn">ELECTRONICS</a>
      </div>

</section>