
<section class="log-container">

   <form action="" method="POST">
      <h3>Login Now</h3>
      <input type="email" name="email" class="box" placeholder="Enter Your Email" required>
      <input type="password" name="pass" class="box" placeholder="Enter Your Password" required>
      <input type="submit" value="login now" class="btn" name="submit">
      <p>Don't have an Account? <a href="register.php">Register Now</a></p>
   </form>

</section>

    <script>
		$('section').ripples({
			resolution: 512,
			dropRadius: 20, //px
			perturbance: 0.04,
		});
    </script>


</body>
</html>