
<div class="shop-bg">

<div class="headingshop">
   <h3>OUR SHOP</h3>
   <p> <a href="home.php">Home</a> / SHOP </p>
</div>

</div>

<section class="p-category">

   <a href="category.php?category=fashion-item">FASHION ITEM</a>
   <a href="category.php?category=clothes">CLOTHES</a>
   <a href="category.php?category=shoes">SHOES</a>
   <a href="category.php?category=electronics">ELECTRONICS</a>

</section>

<section class="products">

   <h1 class="title">latest products</h1>

   <div class="box-containerrr">

   <?php
      $select_products = $conn->prepare("SELECT * FROM `products`");
      $select_products->execute();
      if($select_products->rowCount() > 0){
         while($fetch_products = $select_products->fetch(PDO::FETCH_ASSOC)){ 
   ?>
   <form action="" class="box" method="POST">
      <div class="price">$<span><?= $fetch_products['price']; ?></span>/-</div>
      <a href="view_page.php?pid=<?= $fetch_products['id']; ?>" class="fas fa-eye"></a>
      <img src="uploaded_img/<?= $fetch_products['image']; ?>" alt="">
      <div class="name"><?= $fetch_products['name']; ?></div>
      <input type="hidden" name="pid" value="<?= $fetch_products['id']; ?>">
      <input type="hidden" name="p_name" value="<?= $fetch_products['name']; ?>">
      <input type="hidden" name="p_price" value="<?= $fetch_products['price']; ?>">
      <input type="hidden" name="p_image" value="<?= $fetch_products['image']; ?>">
      <input type="number" min="1" value="1" name="p_qty" class="qty">
      <input type="submit" value="❤" class="readbtnne" name="add_to_wishlist">
      <input type="submit" value="add to cart" class="proceed-btn" name="add_to_cart">
   </form>
   <?php
      }
   }else{
      echo '<p class="empty">no products added yet!</p>';
   }
   ?>

   </div>

</section>

<?php include 'footer.phtml'; ?>

<script src="js/script.js"></script>

</body>
</html>